// <auto-generated />
using System;
using BusTicketBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusTicketBooking.Infrastructure.Migrations
{
    [DbContext(typeof(TicketBookingContext))]
    partial class TicketBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusTicketBooking.Core.Entities.BookingStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusCapacitySeatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArrived")
                        .HasColumnType("bit");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.HasIndex("BusCapacitySeatId");

                    b.ToTable("BookingStatuses");
                });

            modelBuilder.Entity("BusTicketBooking.Core.Entities.BusCapacity", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookedStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("LockedStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SeatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.ToTable("BusCapacities");
                });

            modelBuilder.Entity("BusTicketBooking.Core.Entities.BookingStatus", b =>
                {
                    b.HasOne("BusTicketBooking.Core.Entities.BusCapacity", "BusCapacity")
                        .WithMany("BookingStatus")
                        .HasForeignKey("BusCapacitySeatId");

                    b.Navigation("BusCapacity");
                });

            modelBuilder.Entity("BusTicketBooking.Core.Entities.BusCapacity", b =>
                {
                    b.Navigation("BookingStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
